version: '3'

services:
  postgres-db:
    image: postgres:16
    platform: linux/amd64
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: arena_user
      POSTGRES_DB: arena_hub
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - ./dump/:/docker-entrypoint-initdb.d/
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - arena_dev

  redis:
    image: redis:6.2
    container_name: redis
    restart: unless-stopped
    environment:
      REDIS_PASS: ${REDIS_PASS}
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
    command: [ "redis-server", "/etc/redis/redis.conf" ]
    ports:
      - 6379:6379
    networks:
      - arena_dev

#  akita:
#    container_name: akita
#    image: akitasoftware/cli:latest
#    depends_on:
#      - java-app
#    environment:
#      - AKITA_API_KEY_ID=${AKITA_API_KEY_ID}
#      - AKITA_API_KEY_SECRET=${AKITA_API_KEY_SECRET}
#    network_mode: "service:java-app"
#    entrypoint: /akita apidump --service local-hub

  mvn-migrations:
    image: maven
    platform: linux/amd64
    command:
      - "sh"
      - "-c"
      - "mvn compile && mvn liquibase:update -Dliquibase.url=jdbc:postgresql://postgres-db:5432/arena_hub"
    networks:
      - arena_dev
    depends_on:
      - postgres-db
    volumes:
      - ../guide-core-java/guidecore-migration/:/usr/src/mymaven
    working_dir: /usr/src/mymaven

  java-app:
    image: arena-be-java:2.1
    platform: linux/amd64
    build:
      context: ../guide-core-java/guidecore-server
      dockerfile: ./Dockerfile.local
    container_name: arena-java-app
    # restart: unless-stopped
    ports:
      - 9999:9999
    depends_on:
      - postgres-db
      - redis
    networks:
      - arena_dev
    env_file:
      - .local.env
    environment:
      START_ENVIRONMENT: environmentVars,local,swagger
      GUIDE_API_PORT: '9999'
      REDIS_HOST: redis
      REDIS_PASS: ${REDIS_PASS}
      REDIS_PORT: '6379'
      REDIS_SSL: 'false'
      POSTGRES_HOST: postgres-db
      POSTGRES_USER: arena_user
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_DB_NAME: arena_hub
      POSTGRES_PORT: '5432'
      POSTGRES_SSL: 'false'
      GUIDE_USER_STORE_PRIVATE_KEY: ${GUIDE_USER_STORE_PRIVATE_KEY}
      AWS_ROLE_SESSION_NAME: S3Upload
      AWS_S3_BUCKET: bucket name
      AWS_S3_REGION: eu-west-2
      AWS_IAM_ROLE: iam role
      GUIDE_USER_STORE_DOMAIN: storage-arena.dev.k8s.powtoon.com
      GUIDE_USER_STORE_KEY_PAIR_ID: ${GUIDE_USER_STORE_KEY_PAIR_ID}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
      SENTRY_DSN: ${SENTRY_DSN}
      APP_ENV: local
      ARENA_BACKEND_VERSION: 1.0.0
      BI_TRACKING_HOST: https://example.com

networks:
  arena_dev:
    name: arena_dev
volumes:
  pg_data:
