server:
  port: 80
  servlet:
    context-path: /hub
frontendPath: /arena-hub

spring:
  time-zone: GMT
  resources:
    #配置静态资源路径
    static-locations: classpath:/static/,classpath:/public/,file:${web.profile-path:config/static}
  redis:
    password: kyle2020TBfIU584
    host: master.powtoon-guide-redis-stage.gzxdqo.euw2.cache.amazonaws.com
    port: 6379
    ssl: true
    jedis:
      pool:
        max-active: 5000
        max-wait: -1
        max-idle: 30
        min-idle: 5
    timeout: 50000
    database: 9
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://powtoon-guide-db-stage2.couriexnjxmr.eu-west-2.rds.amazonaws.com:3306/powtoon_guide_db_stage?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT&allowMultiQueries=true
    username: admin
    password: "l22aA7L44imcyjOmT326"
    druid:
      # 初始连接数
      initial-size: 10
      # 最大连接池数量
      max-active: 100
      # 最小连接池数量
      min-idle: 10
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true

aws:
  durationSeconds: 900
  region: us-east-1
  roleArn: arn:aws:iam::369576378958:role/S3UploadRole
  roleSessionName: S3Upload
  bucketName: powtoon-store-stage

#powtoon config
#redirectUri: https://userpt.govidigo.cn/,https://dev.demoguide.xyz/,https://stage.guide.staging.powtoon.com/,https://stage.demoguide.xyz/
clientId: iH1ZRABwPQ3cNzRQmdV8rptrL4gXC0AL8hrvjr2T
ptRootURL: https://arenaec-org2.dev-public.k8s.powtoon.com
oauthToken: /api/v1.0/oauth/token
userUrl: /api/v1.0/integrations/portal/users/me
logOut: /api/v1.0/oauth/revoke_token
videoUrl: /api/v2/powtoons/{id}/player-page
groups: /api/v2/org/groups
#暂无用
clientSecret: D5y3mtfinzLBQJtq0nTjReppDACazBYoASraMWT5KlT2NPsvAKdSyyvMBbNz114D0pHUjnhy3uOWyUCnfr7jpnViaI94IJC2Qvm3os3r83o7U9LjEiMHaxFqbdVkj46N
logoutUrl: /account/logout?next_page=/arena-hub/
#powtoon的首页写死的频道ids
channel:
  channelIdList :
    # id = masterid，channelIds= course id
    - id: 207
      channelIds: 1805,1806,1809
    - id: 208
      channelIds: 1772,1773
#S3 cloudfront signed url
uploadsignurl:
  distributionDomain: stage.store.demoguide.xyz
  privateKeyFilePath: dev-stage_signed_links_private_key.der
  keyPairId: K1JQYEVI2UZJ98
  limitToIpAddressCIDR: 0.0.0.0/0

sitemap:
  defaultId: 207
  siteUrl: stage.demoguide.xyz

permit:
  apiKey: permit_key_ZW0KTH0icmdLZbJvG1fDN4JUMNS4OMMnRZBC3gyj7qSmkisJZR4K2ngtQs1932Mam5qIOpF5ySxy5tegMZXR8y
  pdpAddress: http://47.111.191.189:7766
  # 0 = 开；1=关，不调用permit
  permitSwitch: 1
registercode: xxx

metaurl:
  course: "course"
  courseStatics: "course-statics"
  courseVideo: "course-video"
  channel: "channel"
  playlist: "playlist"
  playlistVideo: "playlist-video"