server:
   port: ${GUIDE_API_PORT:80}
   servlet:
      context-path: /arena-hub
frontendPath: /arena-hub
spring:
   time-zone: GMT
   resources:
       #Configure static resource path
       static-locations: classpath:/static/,classpath:/public/,file:${web.profile-path:config/static}
   redis:
     password: ${REDIS_PASS}
     host: ${REDIS_HOST}
     port: ${REDIS_PORT:6379}
     ssl: ${REDIS_SSL:false}     
     jedis:
       pool:
         max-active: 5000
         max-wait: -1
         max-idle: 30
         min-idle: 5
     timeout: 50000
     database: 9
   datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT:5432}/${POSTGRES_DB_NAME}?charSet=utf8&ssl=${POSTGRES_SSL:false}&ApplicationName=ArenaHub
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASS}
      druid: 
            initial-size: 10
            max-active: 100
            min-idle: 10
            max-wait: 60000
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            # Configure the interval between detection and detection of idle connections that need to be closed. The unit is milliseconds.
            timeBetweenEvictionRunsMillis: 60000
            # Configure the minimum survival time of a connection in the pool, the unit is milliseconds
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: false
                wall:
                    config:
                        multi-statement-allow: true
       
aws:
  s3:
    accessKey: ${AWS_S3_ACCESS_KEY_ID}
    secretAccessKey: ${AWS_S3_SECRET_ACCESS_KEY}
    frontendBucketName: site/arena-hub
  durationSeconds: 900
  region: ${AWS_S3_REGION}
  roleArn: ${AWS_IAM_ROLE}
  roleSessionName: ${AWS_ROLE_SESSION_NAME}
  bucketName: ${AWS_S3_BUCKET}

#powtoon config
oauthToken: /api/v1.0/oauth/token
userUrl: /api/v1.0/users/me/profile
logOut: /api/v1.0/oauth/revoke_token
videoUrl: /api/v2/powtoons/{id}/player-page
groups: /api/v2/org/groups
logoutUrl: /account/logout?next_page=/arena-hub/
#S3 cloudfront signed url
uploadsignurl:
  distributionDomain: ${GUIDE_USER_STORE_DOMAIN}
  privateKeyFilePath: ${GUIDE_USER_STORE_PRIVATE_KEY}
  keyPairId: ${GUIDE_USER_STORE_KEY_PAIR_ID}
  limitToIpAddressCIDR: 0.0.0.0/0

sitemap:
  defaultId: 228
  siteUrl: guide.i10s.onearena.io
  
permit:
  apiKey: ${PDP_API_KEY}
  pdpAddress: ${PDP_ADDRESS}
  # 0 = on; 1 = off, do not call permit
  permitSwitch: 0
registercode: ${REGISTER_CODE}

metaurl:
  course: "course"
  courseStatics: "course-statics"
  courseVideo: "course-video"
  channel: "channel"
  playlist: "playlist"
  playlistVideo: "playlist-video"

bi:
  tracking:
    host: ${BI_TRACKING_HOST}