-- liquibase formatted sql

-- changeset adel:base-1
CREATE TABLE gc_access (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', master_id INT NOT NULL, role_type BIT(1) NULL COMMENT '角色类型', admin_id INT NULL COMMENT 'gc_access的admin_id', code VARCHAR(55) NOT NULL COMMENT 'code', package_learning_hours DOUBLE NULL, subject_json JSON NOT NULL COMMENT 'json', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, create_time timestamp DEFAULT NOW() NOT NULL, code_type INT DEFAULT 0 NULL COMMENT '0为用户注册码、1为门户注册码', free_flag INT NULL COMMENT '1为免费，0为付费', package_name VARCHAR(255) NULL COMMENT '套餐名', package_price_period JSON NULL COMMENT '价格以及价格period', package_description TEXT NULL COMMENT '套餐描述', package_additional_course_information TEXT NULL COMMENT '套餐额外课程信息', package_img_id INT NULL COMMENT '套餐封面文件id', package_show_flag INT NULL, package_video_file_id INT NULL, `order` INT NULL COMMENT '支付包排序', try_for_free_link VARCHAR(255) NULL, try_for_free_text VARCHAR(255) NULL, must_subject_json JSON NULL COMMENT '必须学习的课程', may_subject_json JSON NULL COMMENT '有权限的课程', channel_json JSON NULL COMMENT 'channelJson', group_name VARCHAR(100) NULL COMMENT '组名称', subscribe_json JSON NULL, role_json JSON NULL COMMENT '角色列表', super_teacher INT NULL COMMENT '超级老师0是 1否', CONSTRAINT PK_GC_ACCESS PRIMARY KEY (id));
CREATE TABLE gc_category (id INT NOT NULL, category_name VARCHAR(255) NULL, pid INT NULL, level INT NULL, update_time datetime NULL, create_time datetime NULL, `order` INT NULL, file_name VARCHAR(255) NULL, CONSTRAINT PK_GC_CATEGORY PRIMARY KEY (id));
CREATE TABLE gc_chat_history (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', history_id VARCHAR(64) NULL COMMENT '前段传的history_id', list_chat_id VARCHAR(64) NULL COMMENT 'chat_list关联id', type INT NULL COMMENT '类型，文本=0，问题
=1，学习计划=2', `role` INT NULL COMMENT '角色，系统消息System = 0；用户消息User = 1；gpt消息Assistant = 2', name VARCHAR(3000) NULL COMMENT '名称', text LONGTEXT NULL COMMENT '文字，type=2时', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL COMMENT '修改时间', create_time timestamp DEFAULT NOW() NOT NULL COMMENT '创建时间', CONSTRAINT PK_GC_CHAT_HISTORY PRIMARY KEY (id)) COMMENT='聊天记录';
CREATE TABLE gc_chat_list (id INT AUTO_INCREMENT NOT NULL, chat_id VARCHAR(64) NULL COMMENT 'chatid', text LONGTEXT NULL COMMENT '文字，type=2时', video_id INT NULL, master_id INT NULL, user_id INT NULL, update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL COMMENT '修改时间', create_time timestamp DEFAULT NOW() NOT NULL COMMENT '创建时间', user_role TINYINT(3) NULL COMMENT '1门户，2 or null用户', CONSTRAINT PK_GC_CHAT_LIST PRIMARY KEY (id)) COMMENT='聊天列表';
CREATE TABLE gc_course_cate (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', parent_id INT NULL COMMENT '父级ID', type_name VARCHAR(255) NULL COMMENT '类型名称', create_time timestamp DEFAULT null on update CURRENT_TIMESTAMP NULL COMMENT '创建时间', update_time timestamp DEFAULT null on update CURRENT_TIMESTAMP NULL COMMENT '更新时间', CONSTRAINT PK_GC_COURSE_CATE PRIMARY KEY (id));
CREATE TABLE gc_course_complete_read (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', user_id INT NULL COMMENT '用户id', subject_id INT NULL COMMENT '课程id', target_user_id INT NULL COMMENT '当前老师id', is_read TINYINT(3) NULL COMMENT '是否已读1代表已读0代表未读', type TINYINT(3) NULL COMMENT '类型1代表WorkbooksCompletion2代表CompletedCourses', master_id INT NULL COMMENT 'master的id', create_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NULL COMMENT '创建时间', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NULL COMMENT '修改时间', CONSTRAINT PK_GC_COURSE_COMPLETE_READ PRIMARY KEY (id)) COMMENT='信息已读表';
CREATE TABLE gc_event (id INT AUTO_INCREMENT NOT NULL COMMENT 'id', video_id INT NOT NULL COMMENT '视频ID', event_type TINYINT(3) NULL COMMENT '问题类型', event_time INT NOT NULL COMMENT '弹出时间点，单位秒', time_limit INT DEFAULT 0 NOT NULL COMMENT '操作时间限制，单位秒', ext JSON NULL COMMENT '额外字段', event_title VARCHAR(5000) NULL, link_file_id INT NULL COMMENT '事件从sys_file获取的链接', link_video_id INT NULL COMMENT '事件链接视频gc_video的id', future_pre_event_id INT NULL COMMENT '未来事件的前置事件id', future_delay_time DOUBLE(30, 2) NULL COMMENT '未来事件延迟时间，单位小时', `order` INT DEFAULT 0 NOT NULL COMMENT '排序字段', create_time timestamp DEFAULT NOW() NOT NULL COMMENT '创建时间', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间', upload_type INT DEFAULT 1 NULL COMMENT '上传类型，1=门户上传，2=老师添加', upload_user INT NULL COMMENT '上传人', answer_message_flag INT NULL COMMENT '回答问题是否弹出消息提示正确或错误', CONSTRAINT PK_GC_EVENT PRIMARY KEY (id)) COMMENT='视频下的event';
CREATE TABLE gc_faq (id INT AUTO_INCREMENT NOT NULL, faq_section VARCHAR(255) NOT NULL COMMENT '常见问题类别', faq_title VARCHAR(255) NOT NULL COMMENT '常见问题名称', faq_content VARCHAR(1000) NOT NULL COMMENT '常见问题回答', del_flag INT DEFAULT 1 NOT NULL COMMENT '0为关闭', create_time timestamp DEFAULT NOW() NOT NULL, update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, faq_id INT NULL COMMENT '父级常见问题id', faq_order INT NULL COMMENT '排序字段', CONSTRAINT PK_GC_FAQ PRIMARY KEY (id));
CREATE TABLE gc_feed_back (id INT AUTO_INCREMENT NOT NULL COMMENT '主键id', user_id INT NOT NULL COMMENT '用户id', type INT NOT NULL COMMENT '反馈类型type 0为反馈 1为联系', context VARCHAR(250) NULL COMMENT '反馈内容', file_json JSON NULL COMMENT '文件id json格式', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL COMMENT '修改时间', create_time timestamp DEFAULT NOW() NOT NULL COMMENT '创建时间', CONSTRAINT PK_GC_FEED_BACK PRIMARY KEY (id));
CREATE TABLE gc_group (id INT AUTO_INCREMENT NOT NULL COMMENT 'id', name VARCHAR(55) DEFAULT '' NOT NULL COMMENT '组名', user_access_id INT NOT NULL COMMENT '创建教师的身份', master_id INT NOT NULL COMMENT '创建组的所在空间', sub_ids JSON NOT NULL COMMENT '组的课程权限', code VARCHAR(255) NULL COMMENT 'code', schedule_date JSON NOT NULL COMMENT '日程安排分组', group_access_ids JSON NOT NULL COMMENT '组的学生列表', access_id INT NULL COMMENT '初始化绑定code的gc_access的id', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间', create_time timestamp DEFAULT NOW() NOT NULL COMMENT '创建时间', CONSTRAINT PK_GC_GROUP PRIMARY KEY (id)) COMMENT='教师编辑的组权限';
CREATE TABLE gc_group_mentor (id INT AUTO_INCREMENT NOT NULL, group_id INT NULL, user_access_id INT NULL, off_flag INT NULL, CONSTRAINT PK_GC_GROUP_MENTOR PRIMARY KEY (id));
CREATE TABLE gc_manager (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', sys_id INT NOT NULL COMMENT '实例id', last_name VARCHAR(55) DEFAULT '' NOT NULL COMMENT '名字', first_name VARCHAR(55) DEFAULT '' NOT NULL COMMENT '名字', username VARCHAR(55) NOT NULL COMMENT '用户名', password VARCHAR(55) NOT NULL COMMENT '密码', salt VARCHAR(55) NOT NULL COMMENT '密码盐', state INT NOT NULL COMMENT '状态', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间', create_time timestamp DEFAULT NOW() NOT NULL COMMENT '创建时间', level INT DEFAULT 0 NULL COMMENT '0=门户管理员，1=门户用户', master_id INT NULL, super_admin_flag INT NULL COMMENT '0或null为普通门户管理员，1为超级管理员', CONSTRAINT PK_GC_MANAGER PRIMARY KEY (id)) COMMENT='商户管理员';
CREATE TABLE gc_manager_collection (id INT AUTO_INCREMENT NOT NULL, last_name VARCHAR(255) NULL, first_name VARCHAR(255) NULL, email VARCHAR(255) NULL, phone VARCHAR(255) NULL, update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间', create_time timestamp DEFAULT NOW() NOT NULL COMMENT '创建时间', CONSTRAINT PK_GC_MANAGER_COLLECTION PRIMARY KEY (id)) COMMENT='预注册客户收集';
CREATE TABLE gc_master (id INT AUTO_INCREMENT NOT NULL COMMENT 'id', manager_id INT NULL COMMENT '管理员Id', state TINYINT(3) NOT NULL COMMENT '状态0，1。空间是否关闭', org_name VARCHAR(1000) DEFAULT '' NOT NULL COMMENT '机构名称', portal_name VARCHAR(1000) DEFAULT '' NOT NULL COMMENT '站点标题', context VARCHAR(55) NULL COMMENT '站点context', logo_id INT DEFAULT 0 NOT NULL COMMENT '文件Id', logo_url VARCHAR(255) DEFAULT '' NOT NULL COMMENT 'logo图片url', template_id INT DEFAULT 1 NOT NULL COMMENT '首页样式id', intro_video_id INT NULL COMMENT '门户介绍视频id', source_type TINYINT(3) NULL COMMENT 'null或1:本地intro_video_id不为空，2:youku，3:screenRock，2和3时intro_video_id为空，source_url不为空', source_url VARCHAR(255) NULL COMMENT '源地址  当第三方视频引用的时候', ext_var JSON NULL COMMENT '额外的变量', intro_done_step JSON NULL COMMENT '门户指引步骤完成情况', calendar_link VARCHAR(1000) NULL COMMENT '外部日历链接', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, create_time timestamp DEFAULT NOW() NOT NULL, color VARCHAR(255) NULL COMMENT '主题颜色参数', profile_photo_id INT NULL, brand_description VARCHAR(5000) NULL, brand_tagline VARCHAR(1000) NULL, answer_show_flag INT NULL COMMENT '1为展示，0或null为不展示', connected_account_id VARCHAR(55) NULL, ability_split_funds_flag INT NULL, email_cc JSON NULL COMMENT '抄送邮件地址', admin_logo_file_id INT NULL COMMENT 'pt门户端logoid', board_id BIGINT NULL, favicon_logo_file_id INT NULL, sso_url VARCHAR(255) NULL, sso_client_id VARCHAR(255) NULL, sso_secret VARCHAR(255) NULL, channel_ids JSON NULL, redirect_url VARCHAR(255) NULL, gpt_state TINYINT(3) NULL COMMENT '默认关闭 开=1，关=null、-1、无值', CONSTRAINT PK_GC_MASTER PRIMARY KEY (id), UNIQUE (manager_id)) COMMENT='主站点实例';
CREATE TABLE gc_master_active (id INT AUTO_INCREMENT NOT NULL, master_id INT NOT NULL COMMENT '主站id', type TINYINT(3) NOT NULL COMMENT '0:主站全部解锁1:sub,2:video', ret_id INT NULL COMMENT '根据type,对应的id', activate_size DECIMAL(10, 2) NOT NULL COMMENT '解锁要求', video_id INT NULL COMMENT '视频id', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, create_time timestamp DEFAULT NOW() NOT NULL, CONSTRAINT PK_GC_MASTER_ACTIVE PRIMARY KEY (id)) COMMENT='Master里面资源解锁的配置表';
CREATE TABLE gc_master_home_info (id INT AUTO_INCREMENT NOT NULL COMMENT 'id', master_id INT NOT NULL COMMENT '门户Id', name VARCHAR(55) DEFAULT '' NOT NULL COMMENT '内容名称，', `order` INT NULL COMMENT '各组内部排序', type TINYINT(3) NULL COMMENT '文件类型-枚举', content TEXT NULL COMMENT '文字内容', file_id INT NULL COMMENT 'type=2或3时的文件id', state TINYINT(3) NULL COMMENT '逻辑删除,-1=关闭', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, create_time timestamp DEFAULT NOW() NOT NULL, channel_ids JSON NULL, CONSTRAINT PK_GC_MASTER_HOME_INFO PRIMARY KEY (id)) COMMENT='门户首页信息';
CREATE TABLE gc_master_log (id INT AUTO_INCREMENT NOT NULL, manager_id INT NOT NULL, master_id INT NOT NULL, action_type TINYINT(3) NOT NULL, action_message JSON NOT NULL, update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, create_time timestamp DEFAULT NOW() NOT NULL, CONSTRAINT PK_GC_MASTER_LOG PRIMARY KEY (id)) COMMENT='管理员操作日志';
CREATE TABLE gc_master_message (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL COMMENT '影响的主体用户：该用户导致事件发生', master_id INT NOT NULL COMMENT '空间id', target_user_id INT NULL, event_type TINYINT(3) NULL COMMENT '0文字,1图片,2视频,3声音,4文件,5问题回答,6ScreenRock链接,与gc_user_event_resource的type一致', res_id INT NULL COMMENT 'gc_user_event_resource的id', user_answer_id INT NULL COMMENT 'gc_user_answer的id', user_schedule_id INT NULL COMMENT 'gc_user_schedule的id', video_comment_id INT NULL COMMENT 'gc_video_comment的id 视频评论id', user_note_comment_id INT NULL COMMENT 'gc_user_note_comment的id 作业本回答评论id', message VARCHAR(255) DEFAULT '' NOT NULL COMMENT '消息', read_state BIT(1) DEFAULT 0 NOT NULL COMMENT '0:未读1:已读', create_time timestamp DEFAULT NOW() NOT NULL, update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, CONSTRAINT PK_GC_MASTER_MESSAGE PRIMARY KEY (id)) COMMENT='空间中系统通知事件';
CREATE TABLE gc_master_pay_records (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', price DECIMAL(11, 2) NULL, master_id INT NULL, subject_id INT NULL COMMENT '课程id', user_id INT NULL, order_id VARCHAR(50) NULL COMMENT '订单号', state INT NULL COMMENT '购买状态 0 购买失败 1购买成功', create_time timestamp DEFAULT NOW() NULL, update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NULL, CONSTRAINT PK_GC_MASTER_PAY_RECORDS PRIMARY KEY (id));
CREATE TABLE gc_master_sales_page (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', section_type_id INT NULL COMMENT '关联section类型表ID', subject_id INT NULL COMMENT '课程id', `order` INT NULL COMMENT '总排序', context_json VARCHAR(400) NULL COMMENT '模板内容', state INT NULL COMMENT '状态：0关闭  1启用', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NULL, create_time timestamp DEFAULT NOW() NULL, CONSTRAINT PK_GC_MASTER_SALES_PAGE PRIMARY KEY (id));
CREATE TABLE gc_master_section_type (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', section_number INT NULL COMMENT 'section编号', section_name VARCHAR(255) NULL COMMENT 'section名字', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NULL, create_time timestamp DEFAULT NOW() NULL, state INT NULL COMMENT '状态：0关闭  1启用', CONSTRAINT PK_GC_MASTER_SECTION_TYPE PRIMARY KEY (id));
CREATE TABLE gc_paypal_info (id INT AUTO_INCREMENT NOT NULL, master_id INT NOT NULL COMMENT '门户id', email VARCHAR(255) NULL, username VARCHAR(255) NULL, password VARCHAR(255) NULL, signature VARCHAR(255) NULL, update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, create_time timestamp DEFAULT NOW() NOT NULL, CONSTRAINT PK_GC_PAYPAL_INFO PRIMARY KEY (id), UNIQUE (master_id));
CREATE TABLE gc_problem (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', title VARCHAR(50) NOT NULL COMMENT '常见问题标题', context VARCHAR(250) NOT NULL COMMENT '常见问题内容', status INT DEFAULT 1 NOT NULL COMMENT '0为关闭', create_time timestamp DEFAULT NOW() NOT NULL COMMENT '创建时间', update_time timestamp DEFAULT NOW() NOT NULL COMMENT '修改时间', CONSTRAINT PK_GC_PROBLEM PRIMARY KEY (id));
CREATE TABLE gc_resource (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', video_id INT NOT NULL COMMENT '视频id', resource_name VARCHAR(5000) NULL, file_id INT DEFAULT 0 NOT NULL COMMENT '文件id', resource_type INT NOT NULL COMMENT '资源类型 1:文件，2:引用', res_url VARCHAR(255) DEFAULT '' NOT NULL COMMENT 'url链接', if_end_popup TINYINT(3) NULL COMMENT '是否在视频结束后弹出，1=是', create_time timestamp DEFAULT NOW() NOT NULL, update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, CONSTRAINT PK_GC_RESOURCE PRIMARY KEY (id));
CREATE TABLE gc_social_media (id INT AUTO_INCREMENT NOT NULL, master_id INT NOT NULL COMMENT '门户id', file_id INT NULL COMMENT '文件id', name VARCHAR(20) NOT NULL COMMENT '社交媒体名称', link VARCHAR(32) NOT NULL COMMENT '链接', type INT NULL COMMENT '1=链接，file_id可空，2=图片，link可空', on_off INT NULL COMMENT '-1=关闭', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, create_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, CONSTRAINT PK_GC_SOCIAL_MEDIA PRIMARY KEY (id));
CREATE TABLE gc_subject (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', master_id INT NOT NULL, name VARCHAR(1000) NULL, name_index VARCHAR(1000) NULL COMMENT '课程index，单个门户内唯一', `description` VARCHAR(5000) NULL, type INT DEFAULT 0 NOT NULL COMMENT '主题类型0为科目1为主题', sub_id INT NULL, level INT DEFAULT 0 NOT NULL COMMENT '层级0为顶层', fid INT NULL, alias_sub_id INT NULL COMMENT '重命名课程id', `order` INT DEFAULT 0 NOT NULL COMMENT '排序字段', sub_img_id INT NULL COMMENT 'Subject科目图片', state TINYINT(3) DEFAULT 1 NOT NULL COMMENT '状态: 0=隐藏，1或空=开', token VARCHAR(100) NULL COMMENT '其他课程导入该课程的代码token', is_public TINYINT(3) NULL COMMENT '该课程是否是公共课程，1=是，如是其他课程导入该课程不需要token', master_type_id JSON NULL COMMENT '课程类型id', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, create_time timestamp DEFAULT NOW() NOT NULL, intro_on_off INT NULL COMMENT '是否需要课程介绍页面，1=需要，null=不需要', template_id INT DEFAULT 1 NOT NULL COMMENT '首页样式id', course_tagline VARCHAR(255) NULL COMMENT '课程标语', language VARCHAR(11) NULL, cate_id INT NULL, course_tags JSON NULL, certificates_flag INT NULL, color VARCHAR(255) NULL COMMENT '课程字体颜色', cpd_hours DECIMAL(10, 2) NULL COMMENT '课程时间', cpd_flag INT NULL, badge_id INT NULL, subdetail_img_id JSON NULL, badge_content VARCHAR(255) NULL, create_user INT NULL, available_type INT NULL COMMENT '发布类型', published_user_id INT NULL COMMENT '发布者id', published_time timestamp NULL COMMENT '发布时间', answer_show_flag INT NULL COMMENT '课程回答开关1开,0关,-1跟随门户', CONSTRAINT PK_GC_SUBJECT PRIMARY KEY (id), UNIQUE (token));
CREATE TABLE gc_subject_association (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', master_id INT NOT NULL, `order` INT DEFAULT 0 NOT NULL COMMENT '排序字段', subject_id INT NULL COMMENT '关联课程的gc_subject的id', state TINYINT(3) DEFAULT 1 NOT NULL COMMENT '状态: 0=隐藏，1或空=开', relation_type TINYINT(3) NULL COMMENT '关联课程的关联关系，1=导入import，2=别名alias', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, create_time timestamp DEFAULT NOW() NOT NULL, CONSTRAINT PK_GC_SUBJECT_ASSOCIATION PRIMARY KEY (id)) COMMENT='课程门户关联表';
CREATE TABLE gc_subject_complete (id INT AUTO_INCREMENT NOT NULL, subject_id INT NULL, subject_state INT NULL COMMENT '完成状态 1完成 0未完成 2已开始', master_id INT NULL, user_id INT NULL, create_time datetime DEFAULT null on update CURRENT_TIMESTAMP NULL, update_time datetime DEFAULT null on update CURRENT_TIMESTAMP NULL, in_progress DECIMAL(4, 2) NULL COMMENT '进度', CONSTRAINT PK_GC_SUBJECT_COMPLETE PRIMARY KEY (id));
CREATE TABLE gc_subject_intro_info (id INT AUTO_INCREMENT NOT NULL COMMENT 'id', subject_id INT NULL COMMENT '课程id', name VARCHAR(255) NULL COMMENT '课程介绍页内容名称-枚举', content TEXT NULL COMMENT '课程介绍页文件内容', type TINYINT(3) NULL COMMENT '统一事件类型-枚举', file_id INT NULL COMMENT 'sys_file的id', state TINYINT(3) NULL COMMENT '逻辑删除,0=关闭', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, create_time timestamp DEFAULT NOW() NOT NULL, CONSTRAINT PK_GC_SUBJECT_INTRO_INFO PRIMARY KEY (id)) COMMENT='课程介绍实例';
CREATE TABLE gc_subject_tag_association (id INT AUTO_INCREMENT NOT NULL, tag_id INT NULL COMMENT '对应tag表id', `order` INT NULL COMMENT '排序字段', master_id INT NULL COMMENT '门户id', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, create_time timestamp DEFAULT NOW() NOT NULL, status INT NULL COMMENT '0启用 1关闭', package_status INT NULL COMMENT '是否仅用于支付包判断 0是 null否', close_subject JSON NULL COMMENT '关闭展示课程id', subject_order JSON NULL COMMENT '导入课程下tag课程排序', CONSTRAINT PK_GC_SUBJECT_TAG_ASSOCIATION PRIMARY KEY (id));
CREATE TABLE gc_subject_tags (id INT AUTO_INCREMENT NOT NULL, master_id INT NOT NULL COMMENT '门户id', subject_id INT NOT NULL COMMENT '课程id', tag_text VARCHAR(255) NOT NULL COMMENT '标签', status INT NOT NULL COMMENT '0启用 1关闭', type INT NOT NULL COMMENT '1=主门户，2=导入的门户', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间', create_time timestamp DEFAULT NOW() NOT NULL COMMENT '创建时间', `order` INT NULL COMMENT '排序', close_subject JSON NULL COMMENT '关闭的课程id', subject_order JSON NULL COMMENT 'tag下课程排序', CONSTRAINT PK_GC_SUBJECT_TAGS PRIMARY KEY (id));
CREATE TABLE gc_user (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', sys_id INT NOT NULL COMMENT '系统id', username VARCHAR(55) DEFAULT '' NOT NULL COMMENT '用户名', password VARCHAR(255) DEFAULT '' NOT NULL COMMENT '密码', salt VARCHAR(55) NOT NULL COMMENT '盐', state TINYINT(3) DEFAULT 1 NOT NULL COMMENT '状态', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间', create_time timestamp DEFAULT NOW() NOT NULL COMMENT '创建时间', pid INT NULL COMMENT '父id：老师的id', info_id INT NULL COMMENT '用户信息表ID', pt_user INT NULL COMMENT '1为pt用户', is_valid TINYINT(3) NULL COMMENT '1或null为有效，-1为无效', email_code VARCHAR(55) NULL COMMENT '验证邮箱code', email_codeTime timestamp NULL COMMENT '邮箱code失效时间', CONSTRAINT PK_GC_USER PRIMARY KEY (id));
CREATE TABLE gc_user_access (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', master_id INT NOT NULL COMMENT '主站id', user_id INT NULL COMMENT '用户id', access_id INT NOT NULL COMMENT '访问权限id', state TINYINT(3) DEFAULT 1 NOT NULL COMMENT '1:正常0:停用', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间', create_time timestamp DEFAULT NOW() NOT NULL COMMENT '创建时间', manager_id INT NULL, role_json JSON NULL COMMENT '角色列表', parent_code VARCHAR(100) NULL COMMENT '父级code', CONSTRAINT PK_GC_USER_ACCESS PRIMARY KEY (id)) COMMENT='用户进入空间的注册示例';
CREATE TABLE gc_user_access_active (id INT AUTO_INCREMENT NOT NULL, user_access_id INT NOT NULL, vid INT NOT NULL COMMENT '解锁的视频id', active_amount DECIMAL(10, 2) NOT NULL COMMENT '解锁的金额', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, create_time timestamp DEFAULT NOW() NOT NULL, CONSTRAINT PK_GC_USER_ACCESS_ACTIVE PRIMARY KEY (id)) COMMENT='用户解锁视频记录';
CREATE TABLE gc_user_access_ext (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', user_access_id INT NULL COMMENT 'user_access_id', log_in_time timestamp DEFAULT NOW() NOT NULL COMMENT '登录时间', points DECIMAL(10, 2) NULL COMMENT '用户在门户里面的积分', manager_id INT NULL, CONSTRAINT PK_GC_USER_ACCESS_EXT PRIMARY KEY (id));
CREATE TABLE gc_user_access_invite (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', user_access_id INT NOT NULL, target_access_id INT NOT NULL COMMENT '邀请进来的目标id', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, create_time timestamp DEFAULT NOW() NOT NULL, CONSTRAINT PK_GC_USER_ACCESS_INVITE PRIMARY KEY (id)) COMMENT='邀请进来的列表';
CREATE TABLE gc_user_access_log (id INT AUTO_INCREMENT NOT NULL, user_access_id INT NOT NULL, action_type TINYINT(3) NOT NULL COMMENT '操作类型', action_message JSON NOT NULL COMMENT '操作记录', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, create_time timestamp DEFAULT NOW() NOT NULL, CONSTRAINT PK_GC_USER_ACCESS_LOG PRIMARY KEY (id)) COMMENT='用户操作日志';
CREATE TABLE gc_user_access_permission (id INT AUTO_INCREMENT NOT NULL COMMENT 'id', user_access_id INT NOT NULL COMMENT '用户userAccessId', sub_permission JSON NOT NULL COMMENT '用户权限表', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间', create_time timestamp DEFAULT NOW() NOT NULL, short_term_permission JSON NULL COMMENT '非一次性的课程', channel_permission JSON NULL, subscribe_permission JSON NULL, must_subject_json JSON NULL COMMENT '必须学习的课程', may_subject_json JSON NULL COMMENT '有权限的课程', CONSTRAINT PK_GC_USER_ACCESS_PERMISSION PRIMARY KEY (id), UNIQUE (user_access_id));
CREATE TABLE gc_user_access_share (id INT AUTO_INCREMENT NOT NULL COMMENT 'id', user_access_id INT NOT NULL COMMENT '分享', share_info JSON NOT NULL COMMENT '分享的信息', respond_size INT DEFAULT 0 NOT NULL COMMENT '被响应的次数', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, create_time timestamp DEFAULT NOW() NOT NULL, CONSTRAINT PK_GC_USER_ACCESS_SHARE PRIMARY KEY (id)) COMMENT='分享记录';
CREATE TABLE gc_user_answer (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', event_id INT NOT NULL, user_id INT NOT NULL, answer_json JSON NOT NULL, update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, create_time timestamp DEFAULT NOW() NOT NULL, master_id INT NULL COMMENT '门户id', CONSTRAINT PK_GC_USER_ANSWER PRIMARY KEY (id)) COMMENT='事件的用户问题回答';
CREATE TABLE gc_user_event (id INT AUTO_INCREMENT NOT NULL, user_id INT NULL COMMENT '用户ID', event_id INT NULL COMMENT '事件ID', state TINYINT(3) DEFAULT 1 NOT NULL COMMENT '1:正常0:停用', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间', create_time timestamp DEFAULT NOW() NOT NULL COMMENT '创建时间', master_id INT NULL COMMENT '门户id', CONSTRAINT PK_GC_USER_EVENT PRIMARY KEY (id)) COMMENT='老师给某些学生及自己添加的问题事件';
CREATE TABLE gc_user_event_resource (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', event_id INT NOT NULL COMMENT '问题，事件Id', target_user_id INT NULL, user_id INT NOT NULL COMMENT '用户id', target_id INT NULL, time_node INT DEFAULT -1 NOT NULL COMMENT '时间节点，0:没有时间，单位s', type TINYINT(3) NULL COMMENT '0文字,1图片,2视频,3声音,4文件,6ScreenRock链接，与gc_master_message的event_type一致5留空', content LONGTEXT NULL, file_id INT NULL, update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, create_time timestamp DEFAULT NOW() NOT NULL, master_id INT NULL COMMENT '门户id', super_teacher_message INT NULL COMMENT '超级老师信息0是 1否', super_teacher_all_message INT NULL COMMENT '超级老师信息发送全体0是 1否', CONSTRAINT PK_GC_USER_EVENT_RESOURCE PRIMARY KEY (id)) COMMENT='事件资源文件';
CREATE TABLE gc_user_fabulous (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL COMMENT '角色id', event_id INT NULL COMMENT '事件id', video_id INT NULL COMMENT '视频id', target_user_id INT NOT NULL COMMENT '被点赞人userId', comment_id INT NOT NULL COMMENT '评论id', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL COMMENT '修改时间', create_time timestamp DEFAULT NOW() NOT NULL COMMENT '创建时间', CONSTRAINT PK_GC_USER_FABULOUS PRIMARY KEY (id));
CREATE TABLE gc_user_info (id INT AUTO_INCREMENT NOT NULL, last_name VARCHAR(255) NULL, first_name VARCHAR(255) NULL, avatar_file_id INT NULL, gender TINYINT(3) NULL COMMENT '性别，1=男，0=女', phone VARCHAR(50) NULL COMMENT '手机号码', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间', create_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL COMMENT 'create_time', CONSTRAINT PK_GC_USER_INFO PRIMARY KEY (id));
CREATE TABLE gc_user_message (id INT UNSIGNED AUTO_INCREMENT NOT NULL COMMENT '主键', user_id INT NOT NULL COMMENT '消息所有用户id', master_id INT NOT NULL COMMENT '主站id', read_state BIT(1) NOT NULL COMMENT '0:未读1:已读', target_user_id INT NULL COMMENT '目标用户id', message VARCHAR(1000) NULL COMMENT '消息内容', file_id INT NULL COMMENT '文件id', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间', create_time timestamp DEFAULT NOW() NOT NULL COMMENT '创建时间', CONSTRAINT PK_GC_USER_MESSAGE PRIMARY KEY (id));
CREATE TABLE gc_user_note (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', video_id INT NOT NULL COMMENT '视频id', user_id INT NOT NULL COMMENT '用户id', note_content TEXT NULL COMMENT '笔记内容', file_id INT NULL COMMENT '文件id', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间', create_time timestamp DEFAULT NOW() NOT NULL COMMENT '创建时间', master_id INT NULL COMMENT '门户id', CONSTRAINT PK_GC_USER_NOTE PRIMARY KEY (id));
CREATE TABLE gc_user_note_comment (id INT AUTO_INCREMENT NOT NULL COMMENT '主键id', user_id INT NOT NULL COMMENT '用户id', target_user_id INT NOT NULL COMMENT '被回复人id', event_id INT NOT NULL COMMENT '事件id', context VARCHAR(1000) NULL COMMENT '回复内容', file_id INT NULL COMMENT '上传文件id', create_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL COMMENT '创建时间', update_time timestamp DEFAULT NOW() NOT NULL COMMENT '修改时间', master_id INT NULL COMMENT '门户id', CONSTRAINT PK_GC_USER_NOTE_COMMENT PRIMARY KEY (id));
CREATE TABLE gc_user_save_content (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', folder_id INT NOT NULL COMMENT '保存文件夹Id', user_id INT NOT NULL COMMENT '用户Id', master_id INT NULL COMMENT '门户id', video_id INT NULL COMMENT '视频Id', sub_id INT NULL COMMENT '课程Id', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, create_time timestamp DEFAULT NOW() NOT NULL, file_id INT NULL COMMENT '文件id', CONSTRAINT PK_GC_USER_SAVE_CONTENT PRIMARY KEY (id)) COMMENT='用户保存的内容';
CREATE TABLE gc_user_save_content_follow (id INT AUTO_INCREMENT NOT NULL, user_id INT NULL, folder_id INT NULL, update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NULL, create_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NULL, CONSTRAINT PK_GC_USER_SAVE_CONTENT_FOLLOW PRIMARY KEY (id));
CREATE TABLE gc_user_save_folder (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', name VARCHAR(55) NULL COMMENT '文件夹名称', user_id INT NOT NULL COMMENT '用户Id', state TINYINT(3) NULL COMMENT '状态: 0=隐藏，1或空=开', file_id INT NULL COMMENT '封面图片文件id', master_id INT NULL COMMENT '门户id', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, create_time timestamp DEFAULT NOW() NOT NULL, if_private INT NULL COMMENT '1代表隐藏，0和null代表显示', CONSTRAINT PK_GC_USER_SAVE_FOLDER PRIMARY KEY (id)) COMMENT='用户保存的视频的文件夹';
CREATE TABLE gc_user_schedule (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', name VARCHAR(55) NULL COMMENT '日程计划名称', user_id INT NULL, group_id INT NULL COMMENT '班级id', sub_id INT NULL COMMENT '课程id', video_id INT NULL COMMENT '视频id', level TINYINT(3) NULL COMMENT '1=1级课程，2=2级话题，11=视频', master_id INT NOT NULL COMMENT 'masterId', schedule_json JSON NOT NULL COMMENT '视频列表', addby_user_id INT NULL COMMENT '添加老师的id，如果空则自己给自己添加', start_date date NULL COMMENT '开始日期', end_date date NULL COMMENT '结束日期', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间', create_time timestamp DEFAULT NOW() NOT NULL COMMENT '创建时间', CONSTRAINT PK_GC_USER_SCHEDULE PRIMARY KEY (id));
CREATE TABLE gc_user_stripe (id INT AUTO_INCREMENT NOT NULL, type INT NULL COMMENT '0-stripe', stripe_customer_id VARCHAR(255) NULL, user_id INT NULL, update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, create_time timestamp DEFAULT NOW() NOT NULL, CONSTRAINT PK_GC_USER_STRIPE PRIMARY KEY (id));
CREATE TABLE gc_user_stripe_subscription (id INT AUTO_INCREMENT NOT NULL, user_stripe_id INT NULL, auto_charge_flag INT NULL COMMENT '1代表订阅生效中，0代表不生效', stripe_subscription_json JSON NULL COMMENT 'stripe订阅对象数据', stripe_subscription_id VARCHAR(255) NULL, create_time timestamp DEFAULT NOW() NULL, update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NULL, master_id INT NULL, CONSTRAINT PK_GC_USER_STRIPE_SUBSCRIPTION PRIMARY KEY (id));
CREATE TABLE gc_user_video_action (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', video_id INT NULL, user_id INT NOT NULL COMMENT '用户Id', type TINYINT(3) NULL COMMENT '1=点赞，2=评价', value VARCHAR(500) NULL COMMENT '操作值，1=点赞时为空', star_value FLOAT(12) NULL COMMENT '星级评价值', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, create_time timestamp DEFAULT NOW() NOT NULL, review_title VARCHAR(255) NULL, review_content VARCHAR(255) NULL, sub_id INT NULL, file_id INT NULL, CONSTRAINT PK_GC_USER_VIDEO_ACTION PRIMARY KEY (id)) COMMENT='用户对视频的操作，点赞 或者 收藏 等等';
CREATE TABLE gc_user_video_play (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', video_id INT NULL, file_id INT NULL COMMENT '文件视频id', master_id INT NOT NULL COMMENT '空间id', user_id INT NOT NULL COMMENT '用户id', play_state TINYINT(3) NOT NULL COMMENT '0:播放中1:看完', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间', create_time timestamp DEFAULT NOW() NOT NULL COMMENT '创建时间', CONSTRAINT PK_GC_USER_VIDEO_PLAY PRIMARY KEY (id)) COMMENT='用户对视频的播放记录';
CREATE TABLE gc_user_video_plays_node (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', videoplay_id INT NULL COMMENT '视频播放记录表ID', start_time INT NULL COMMENT '开始时间', end_time INT DEFAULT 0 NULL COMMENT '结束时间', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间', create_time timestamp DEFAULT NOW() NOT NULL COMMENT '创建时间', CONSTRAINT PK_GC_USER_VIDEO_PLAYS_NODE PRIMARY KEY (id));
CREATE TABLE gc_user_weapp (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', uid INT NOT NULL COMMENT '用户id', openid VARCHAR(55) NOT NULL COMMENT '微信号', session_key VARCHAR(55) NOT NULL COMMENT '微信id', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间', create_time timestamp DEFAULT NOW() NOT NULL COMMENT '创建时间', CONSTRAINT PK_GC_USER_WEAPP PRIMARY KEY (id), UNIQUE (uid), UNIQUE (openid));
CREATE TABLE gc_video (id INT AUTO_INCREMENT NOT NULL COMMENT 'id', video_name VARCHAR(3000) NULL, video_name_index VARCHAR(3000) NULL COMMENT '视频index，单个1级课程内唯一', video_desc VARCHAR(4000) NULL, video_time INT DEFAULT 0 NOT NULL COMMENT '视频总时长', file_id INT DEFAULT 0 NOT NULL COMMENT '视频源', source_url VARCHAR(255) DEFAULT '' NOT NULL COMMENT '源地址  当第三方视频引用的时候', video_source TINYINT(3) NULL COMMENT '1:本地 2:腾讯，3:ScreenRock', sub_id INT DEFAULT 0 NOT NULL COMMENT '课程组织下面', `order` INT DEFAULT 0 NOT NULL COMMENT '排序', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, create_time timestamp DEFAULT NOW() NOT NULL, transcript_file_id INT NULL COMMENT '文件信息', transcript_state TINYINT(3) DEFAULT 0 NULL COMMENT '默认为0,0为隐藏1为显示,用于决定是否给用户显示聊天UI', questions JSON NULL COMMENT '默认问题', summary LONGTEXT NULL COMMENT '小结', chat_id VARCHAR(64) NULL COMMENT 'chatid', lesson_plan LONGTEXT NULL COMMENT '课程计划', caption_status INT NULL COMMENT '字幕状态', gpt_info JSON NULL COMMENT '超时时间处理信息', gpt_lang VARCHAR(255) NULL COMMENT 'gpt原字幕语言', CONSTRAINT PK_GC_VIDEO PRIMARY KEY (id));
CREATE TABLE gc_video_comment (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', video_id INT NOT NULL COMMENT '视频id', user_id INT NOT NULL COMMENT '用户id', comment VARCHAR(1000) NULL, file_id INT NULL COMMENT '文件id', reply_comment_id INT NULL COMMENT '被回复的信息id', main_comment_id INT NULL COMMENT '主评论id', target_user_id INT NULL COMMENT '被回复的人id', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, create_time timestamp DEFAULT NOW() NOT NULL, master_id INT NULL COMMENT '门户id', CONSTRAINT PK_GC_VIDEO_COMMENT PRIMARY KEY (id)) COMMENT='视频评论';
CREATE TABLE help_top (id INT NOT NULL, CONSTRAINT PK_HELP_TOP PRIMARY KEY (id));
CREATE TABLE pt_channel (id INT AUTO_INCREMENT NOT NULL, channel_name VARCHAR(255) NULL, channel_img_file_id INT NULL, `desc` VARCHAR(255) NULL, create_user_id INT NULL, visible_flag INT NULL, category_id INT NULL, level INT NULL, fid INT NULL, `order` INT NULL, master_id INT NULL, channel_slug VARCHAR(255) NULL, create_time datetime DEFAULT NOW() NULL, update_time datetime DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NULL, channel_avatar_file_id INT NULL, CONSTRAINT PK_PT_CHANNEL PRIMARY KEY (id));
CREATE TABLE pt_channel_content (id INT AUTO_INCREMENT NOT NULL, channel_id INT NULL, file_id INT NULL, playlist_id INT NULL, section_id INT NULL, content_order INT NULL, create_time datetime DEFAULT NOW() NULL, update_time datetime DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NULL, CONSTRAINT PK_PT_CHANNEL_CONTENT PRIMARY KEY (id));
CREATE TABLE pt_channel_subscribe (id INT AUTO_INCREMENT NOT NULL, user_id INT NULL, channel_id INT NULL, create_time datetime DEFAULT NOW() NULL, update_time datetime DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NULL, CONSTRAINT PK_PT_CHANNEL_SUBSCRIBE PRIMARY KEY (id));
CREATE TABLE pt_config (id INT AUTO_INCREMENT NOT NULL, master_id INT NULL, show_playlists INT NULL, show_search_bar INT NULL, page_header VARCHAR(1000) NULL, page_body VARCHAR(1000) NULL, create_time datetime DEFAULT NOW() NULL, update_time datetime DEFAULT NOW() NULL, CONSTRAINT PK_PT_CONFIG PRIMARY KEY (id));
CREATE TABLE pt_login_config (id INT AUTO_INCREMENT NOT NULL, master_id INT NULL, pt_root_url VARCHAR(255) NULL, client_id VARCHAR(255) NULL, oauth_token VARCHAR(255) NULL, user_url VARCHAR(255) NULL, log_out VARCHAR(255) NULL, client_secret VARCHAR(255) NULL, log_out_url VARCHAR(255) NULL, create_time datetime NULL, update_time datetime NULL, create_by VARCHAR(255) NULL, update_by VARCHAR(255) NULL, `groups` VARCHAR(100) NULL COMMENT '组接口', CONSTRAINT PK_PT_LOGIN_CONFIG PRIMARY KEY (id));
CREATE TABLE pt_tags (id INT AUTO_INCREMENT NOT NULL, master_id INT NOT NULL COMMENT '门户id', subject_id INT NULL COMMENT '课程id', tag_text VARCHAR(255) NOT NULL COMMENT '标签', type INT NOT NULL COMMENT '1=课程tag 2=视频tag 3=资源tag', `order` INT NULL COMMENT '排序', video_id INT NULL COMMENT '视频id', resource_id INT NULL COMMENT '资源id', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间', create_time timestamp DEFAULT NOW() NOT NULL COMMENT '创建时间', channel_id INT NULL, file_id INT NULL COMMENT '文件id', CONSTRAINT PK_PT_TAGS PRIMARY KEY (id));
CREATE TABLE pt_view_subject (id INT AUTO_INCREMENT NOT NULL, subject_id INT NULL COMMENT '课程id', user_id INT NULL COMMENT '用户id', master_id INT NULL COMMENT '门户id', create_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NULL, update_time timestamp DEFAULT NOW() NULL, CONSTRAINT PK_PT_VIEW_SUBJECT PRIMARY KEY (id));
CREATE TABLE schema_version (id INT AUTO_INCREMENT NOT NULL, version INT DEFAULT 0 NULL, git_hash VARCHAR(64) NULL, `description` VARCHAR(64) NULL, installed timestamp DEFAULT NOW() NOT NULL, CONSTRAINT PK_SCHEMA_VERSION PRIMARY KEY (id));
CREATE TABLE sys_business (id INT AUTO_INCREMENT NOT NULL COMMENT '业务id', name VARCHAR(55) NOT NULL COMMENT '业务名称', `key` VARCHAR(55) NOT NULL COMMENT '业务代码', remark VARCHAR(255) DEFAULT '' NOT NULL COMMENT '留言', create_time timestamp DEFAULT NOW() NOT NULL, update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, CONSTRAINT PK_SYS_BUSINESS PRIMARY KEY (id), UNIQUE (`key`)) COMMENT='业务表，用来描述业务';
CREATE TABLE sys_file (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', sys_id INT NOT NULL COMMENT '业务实例id', upload_uid INT NULL COMMENT '上传者Id', user_role INT NULL COMMENT 'upload_uid的角色，1=门户，2=用户', name VARCHAR(2000) NULL, folder VARCHAR(255) NOT NULL COMMENT '文件夹目录', file_url VARCHAR(2000) NULL, file_type VARCHAR(255) DEFAULT '' NOT NULL COMMENT '文件类型', file_type_index INT NULL COMMENT '文件类型，枚举', file_remark JSON NOT NULL COMMENT '文件元数据json', master_id INT NULL COMMENT 'gc_master的id', save_type TINYINT(3) NOT NULL COMMENT '文件储存方式\\n1 disk\\n2 \\n3链接', md5 VARCHAR(255) NULL, size VARCHAR(255) NULL COMMENT '文件大小', video_long INT NULL COMMENT '视频或音频时长，视频时适用', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, create_time timestamp DEFAULT NOW() NOT NULL, if_caption VARCHAR(10) NULL COMMENT '是否开启字幕', target_lang_json VARCHAR(10) NULL COMMENT '翻译后的字幕文件语言', thumb_nail_url VARCHAR(2000) NULL, thumb_nail_id INT NULL COMMENT '缩略图id', upload_file_type VARCHAR(30) NULL COMMENT '区分阿里oss和aws s3', `description` TEXT NULL, uuid VARCHAR(50) NULL COMMENT '唯一id', webm_to_mp4 JSON NULL COMMENT '转码信息', CONSTRAINT PK_SYS_FILE PRIMARY KEY (id));
CREATE TABLE sys_file_caption (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', ym_task_id VARCHAR(50) NULL COMMENT '云猫任务ID', ym_code INT NULL COMMENT '云猫code', ym_srt_data VARCHAR(255) NULL COMMENT 'srt数据', ym_message VARCHAR(255) DEFAULT '' NULL COMMENT '云猫消息', lang VARCHAR(255) NULL COMMENT '原字幕语言', video_id INT NULL COMMENT '视频文件ID', caption_file_id INT NULL COMMENT '字幕文件ID', create_time timestamp DEFAULT NOW() NULL COMMENT '创建时间', update_time timestamp DEFAULT NOW() NULL COMMENT '更新时间', state INT DEFAULT 1 NULL COMMENT '状态0关 1开', CONSTRAINT PK_SYS_FILE_CAPTION PRIMARY KEY (id));
CREATE TABLE sys_menu (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NULL COMMENT '名称', update_name VARCHAR(100) NULL COMMENT '修改后字段', `order` INT NULL COMMENT '排序', update_switch INT NULL COMMENT '修改开关,1是 0否', `key` VARCHAR(255) NULL, parent_id INT NULL, level INT NULL, sort INT NULL, create_time datetime DEFAULT null on update CURRENT_TIMESTAMP NULL, update_time datetime DEFAULT null on update CURRENT_TIMESTAMP NULL, remarks VARCHAR(255) NULL, state INT DEFAULT 0 NULL, master_id INT NULL, CONSTRAINT PK_SYS_MENU PRIMARY KEY (id));
CREATE TABLE sys_module (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', business_id INT NOT NULL COMMENT '业务id', name VARCHAR(50) NOT NULL COMMENT '模块名称', module_code VARCHAR(50) NOT NULL COMMENT '模块代码', remark VARCHAR(255) DEFAULT '' NOT NULL COMMENT '模块说明', parent VARCHAR(50) NOT NULL COMMENT '业务域', create_time timestamp DEFAULT NOW() NOT NULL COMMENT '创建时间', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间', CONSTRAINT PK_SYS_MODULE PRIMARY KEY (id)) COMMENT='系统权限模块表';
CREATE TABLE sys_permission (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', role_id INT NOT NULL COMMENT '角色id', module_id INT NOT NULL COMMENT '模块id', perm_code VARCHAR(55) DEFAULT '' NOT NULL COMMENT '权限功能字符', CONSTRAINT PK_SYS_PERMISSION PRIMARY KEY (id)) COMMENT='角色权限表';
CREATE TABLE sys_role (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', sys_id INT NOT NULL COMMENT '权限', role_name VARCHAR(55) DEFAULT '' NOT NULL COMMENT '角色名', role_key VARCHAR(55) DEFAULT '' NOT NULL COMMENT '角色权限字符串', super_admin TINYINT(3) DEFAULT 0 NOT NULL COMMENT '1:为超级管理员不进行权限验证', remark VARCHAR(255) DEFAULT '' NOT NULL COMMENT '说明', create_time timestamp DEFAULT NOW() NOT NULL COMMENT '创建时间', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间', CONSTRAINT PK_SYS_ROLE PRIMARY KEY (id));
CREATE TABLE sys_role_menu (id INT AUTO_INCREMENT NOT NULL, role_id INT NULL, menu_ids JSON NULL, create_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NULL, update_time timestamp DEFAULT null on update CURRENT_TIMESTAMP NULL, CONSTRAINT PK_SYS_ROLE_MENU PRIMARY KEY (id));
CREATE TABLE sys_system (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', business_id INT NOT NULL COMMENT '业务ID', name VARCHAR(55) DEFAULT '' NOT NULL COMMENT '实例名称', create_time timestamp DEFAULT NOW() NOT NULL COMMENT '创建时间', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间', CONSTRAINT PK_SYS_SYSTEM PRIMARY KEY (id)) COMMENT='系统实例';
CREATE TABLE sys_user (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', sys_id INT NOT NULL COMMENT '系统实例Id', username VARCHAR(12) NOT NULL COMMENT '用户名', password VARCHAR(55) NOT NULL COMMENT '密码字段', salt VARCHAR(55) DEFAULT '' NOT NULL COMMENT '盐', name VARCHAR(55) NOT NULL COMMENT '姓名', phone VARCHAR(15) NOT NULL COMMENT '手机号码', state TINYINT(3) DEFAULT 1 NOT NULL COMMENT '账号的状态', authentication TINYINT(3) DEFAULT 0 NOT NULL COMMENT '认证状态', create_time timestamp DEFAULT NOW() NOT NULL COMMENT '创建时间', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间', CONSTRAINT PK_SYS_USER PRIMARY KEY (id)) COMMENT='系统用户表，统一用户管理
每个用户在学校中的角色会不一样';
CREATE TABLE sys_user_role (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', user_id INT NOT NULL COMMENT '用户id', role_id INT NOT NULL COMMENT '角色id', CONSTRAINT PK_SYS_USER_ROLE PRIMARY KEY (id));
CREATE TABLE sys_user_weapp (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', uid INT NOT NULL COMMENT '用户id', openid VARCHAR(55) DEFAULT '' NOT NULL COMMENT 'openid', session_key VARCHAR(55) DEFAULT '' NOT NULL COMMENT '微信小程序登录态', CONSTRAINT PK_SYS_USER_WEAPP PRIMARY KEY (id), UNIQUE (uid), UNIQUE (openid)) COMMENT='微信小程序用户';
CREATE TABLE sys_weapp (id INT AUTO_INCREMENT NOT NULL COMMENT '主键', sys_id INT NOT NULL COMMENT '系统实例ID', appid VARCHAR(55) DEFAULT '' NOT NULL COMMENT 'appid', secret VARCHAR(55) NOT NULL COMMENT 'secret', create_time timestamp DEFAULT NOW() NOT NULL COMMENT '创建时间', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL COMMENT '更新时间', CONSTRAINT PK_SYS_WEAPP PRIMARY KEY (id), UNIQUE (sys_id)) COMMENT='系统微信appid secret设置';
CREATE TABLE sys_weixin_pay (id INT AUTO_INCREMENT NOT NULL, order_id VARCHAR(50) NOT NULL COMMENT '订单号', prepay_id VARCHAR(255) NULL COMMENT '微信订单下单号', open_id VARCHAR(100) NOT NULL COMMENT 'openId', uid INT DEFAULT 0 NOT NULL COMMENT '用户id', sys_id INT NULL COMMENT 'sysId', currency VARCHAR(11) NULL COMMENT '币种', total_fee DECIMAL(10, 2) NOT NULL COMMENT '付款金额', order_status TINYINT(3) NOT NULL COMMENT '订单状态0:未支付，1:完成2:取消', pay_type INT NULL COMMENT '支付类型 0微信 1支付宝 2paypal 3stripe', update_time timestamp DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP NOT NULL, create_time timestamp DEFAULT NOW() NOT NULL, access_id INT NULL, master_id INT NULL, session_id VARCHAR(255) NULL, session_expire_date INT NULL, split_funds_flag INT NULL, discount_flag INT NULL, total_sub_fee INT NULL, access_expire_time timestamp NULL COMMENT '订阅过期时间', CONSTRAINT PK_SYS_WEIXIN_PAY PRIMARY KEY (id), UNIQUE (order_id), UNIQUE (prepay_id));
ALTER TABLE gc_group_mentor ADD CONSTRAINT gc_mentor_group UNIQUE (group_id, user_access_id);
ALTER TABLE gc_user_stripe ADD CONSTRAINT gc_user_stripe_uid_customer_id UNIQUE (stripe_customer_id, user_id);
ALTER TABLE gc_user_access_invite ADD CONSTRAINT invite_unique UNIQUE (user_access_id, target_access_id);
ALTER TABLE gc_master_home_info ADD CONSTRAINT master_id UNIQUE (master_id, name);
ALTER TABLE gc_subject_association ADD CONSTRAINT master_id UNIQUE (master_id, subject_id);
ALTER TABLE gc_subject_tag_association ADD CONSTRAINT package_status UNIQUE (package_status, master_id, tag_id);
ALTER TABLE gc_subject_intro_info ADD CONSTRAINT subject_id UNIQUE (subject_id, name);
ALTER TABLE gc_user ADD CONSTRAINT sysId_username_unque UNIQUE (sys_id, username);
ALTER TABLE gc_access ADD CONSTRAINT `unique` UNIQUE (master_id, code);
ALTER TABLE gc_group ADD CONSTRAINT `unique` UNIQUE (user_access_id, code);
ALTER TABLE gc_user_answer ADD CONSTRAINT `unique` UNIQUE (event_id, user_id, master_id);
ALTER TABLE gc_user_schedule ADD CONSTRAINT `unique` UNIQUE (user_id, master_id, sub_id);
ALTER TABLE gc_user_video_action ADD CONSTRAINT `unique` UNIQUE (video_id, user_id, type);
ALTER TABLE sys_permission ADD CONSTRAINT `unique` UNIQUE (role_id, module_id, perm_code);
ALTER TABLE sys_user_role ADD CONSTRAINT `unique` UNIQUE (user_id, role_id);
ALTER TABLE pt_channel ADD CONSTRAINT unique_channel_slug UNIQUE (master_id, channel_slug);
ALTER TABLE sys_role ADD CONSTRAINT unique_key UNIQUE (role_key, sys_id);
ALTER TABLE gc_subject_tag_association ADD CONSTRAINT unique_tag UNIQUE (tag_id, master_id);
ALTER TABLE gc_subject_tags ADD CONSTRAINT unique_tag UNIQUE (master_id, subject_id, tag_text);
ALTER TABLE pt_channel_subscribe ADD CONSTRAINT unique_user_channel UNIQUE (user_id, channel_id);
ALTER TABLE gc_manager ADD CONSTRAINT unique_username UNIQUE (username, sys_id);
ALTER TABLE gc_user_event ADD CONSTRAINT userId_eventId_unique UNIQUE (user_id, event_id);
ALTER TABLE gc_user_access ADD CONSTRAINT user_access_id_master_id_fk UNIQUE (master_id, user_id, access_id);
ALTER TABLE sys_user ADD CONSTRAINT username_unique UNIQUE (username, sys_id);
CREATE INDEX access_admin_id ON gc_access(admin_id);
CREATE INDEX access_package_img_id ON gc_access(package_img_id);
CREATE INDEX access_package_video_file_id ON gc_access(package_video_file_id);
CREATE INDEX active_video_id ON gc_master_active(video_id);
CREATE INDEX caption_file_id ON sys_file_caption(caption_file_id);
CREATE INDEX category_file_id ON gc_category(file_name);
CREATE INDEX channel_file_tag_id ON pt_tags(file_id);
CREATE INDEX channel_fileid ON pt_channel_content(file_id);
CREATE INDEX channel_subscribe ON pt_channel_subscribe(channel_id);
CREATE INDEX channel_video_section ON pt_channel_content(section_id);
CREATE INDEX channel_video_unique ON pt_channel_content(channel_id, file_id);
CREATE INDEX chat_id ON gc_chat_list(chat_id);
CREATE INDEX chat_master_id ON gc_chat_list(master_id);
CREATE INDEX chat_user_id ON gc_chat_list(user_id);
CREATE INDEX chat_video_id ON gc_chat_list(video_id);
CREATE INDEX comment_master_id ON gc_video_comment(master_id);
CREATE INDEX fb_user_fk ON gc_feed_back(user_id);
CREATE INDEX file_id ON gc_user_video_play(file_id);
CREATE INDEX fk_association_master_id ON gc_subject_tag_association(master_id);
CREATE INDEX fk_channel_id ON pt_tags(channel_id);
CREATE INDEX fk_master_id_pt ON pt_view_subject(master_id);
CREATE INDEX fk_resource_id ON pt_tags(resource_id);
CREATE INDEX fk_subject_id ON pt_tags(subject_id);
CREATE INDEX fk_subject_id_pt ON pt_view_subject(subject_id);
CREATE INDEX fk_thumb_nail_id ON sys_file(thumb_nail_id);
CREATE INDEX fk_user_id ON gc_subject(create_user);
CREATE INDEX fk_user_id_pt ON pt_view_subject(user_id);
CREATE INDEX fk_video_id ON pt_tags(video_id);
CREATE INDEX g_master_id_FK ON gc_group(master_id);
CREATE INDEX gc_course_complete_read_subject_id ON gc_course_complete_read(subject_id);
CREATE INDEX gc_course_complete_read_user_id ON gc_course_complete_read(user_id);
CREATE INDEX gc_event_future_pre_event_id ON gc_event(future_pre_event_id);
CREATE INDEX gc_event_link_file_id ON gc_event(link_file_id);
CREATE INDEX gc_event_link_video_id ON gc_event(link_video_id);
CREATE INDEX gc_faq_id ON gc_faq(faq_id);
CREATE INDEX gc_master_id ON pt_login_config(master_id);
CREATE INDEX gc_mentor_user_access_id ON gc_group_mentor(user_access_id);
CREATE INDEX gc_subject_alias_sub_id ON gc_subject(alias_sub_id);
CREATE INDEX gc_subject_fid ON gc_subject(fid);
CREATE INDEX gc_subject_sub_id ON gc_subject(sub_id);
CREATE INDEX gc_tags_subId ON gc_subject_tags(subject_id);
CREATE INDEX gc_transcript_file_id ON gc_video(transcript_file_id);
CREATE INDEX gc_user_save_content_follow_folderid ON gc_user_save_content_follow(folder_id);
CREATE INDEX gc_user_save_content_follow_uid ON gc_user_save_content_follow(user_id);
CREATE INDEX gc_video_file_id ON gc_video(file_id);
CREATE INDEX group_access_id ON gc_group(access_id);
CREATE INDEX home_info_master_id ON gc_master_home_info(master_id);
CREATE INDEX info_avatar_file_id ON gc_user_info(avatar_file_id);
CREATE INDEX list_chat_id ON gc_chat_history(list_chat_id);
CREATE INDEX log_master_id_fk ON gc_master_log(master_id);
CREATE INDEX manager_master_FK ON gc_manager(master_id);
CREATE INDEX master_id ON gc_master_active(master_id);
CREATE INDEX master_message_res_id ON gc_master_message(res_id);
CREATE INDEX master_message_target_user_id ON gc_master_message(target_user_id);
CREATE INDEX master_message_user_answer_id_fk ON gc_master_message(user_answer_id);
CREATE INDEX master_message_user_id ON gc_master_message(user_id);
CREATE INDEX master_message_user_schedule_id_fk ON gc_master_message(user_schedule_id);
CREATE INDEX message_file_id ON gc_user_message(file_id);
CREATE INDEX message_master_id_fk ON gc_master_message(master_id);
CREATE INDEX name_unique ON sys_system(business_id, name);
CREATE INDEX note_file_id ON gc_user_note(file_id);
CREATE INDEX parent_id ON gc_course_cate(parent_id);
CREATE INDEX record_portal_id ON gc_master_pay_records(master_id);
CREATE INDEX record_subject_id ON gc_master_pay_records(subject_id);
CREATE INDEX record_subject_id ON gc_master_sales_page(subject_id);
CREATE INDEX record_subject_id ON gc_master_section_type(section_name);
CREATE INDEX record_user_id ON gc_master_pay_records(user_id);
CREATE INDEX res_video_id ON gc_resource(video_id);
CREATE INDEX section_type_id ON gc_master_sales_page(section_type_id);
CREATE INDEX social_media_master_id ON gc_social_media(master_id);
CREATE INDEX stripe_user_id ON gc_user_stripe_subscription(user_stripe_id);
CREATE INDEX sub_master_id ON gc_subject(master_id);
CREATE INDEX sub_master_id ON gc_subject_association(master_id);
CREATE INDEX subject_file_id ON gc_subject(sub_img_id);
CREATE INDEX subject_import_subject_id ON gc_subject_association(subject_id);
CREATE INDEX subject_intro_info_file_id ON gc_subject_intro_info(file_id);
CREATE INDEX subject_intro_info_subject_id ON gc_subject_intro_info(subject_id);
CREATE INDEX subscription_master_id ON gc_user_stripe_subscription(master_id);
CREATE INDEX sys_file_master_id ON sys_file(master_id);
CREATE INDEX ua_access_fk ON gc_user_access(access_id);
CREATE INDEX ua_master_id_fk ON gc_user_access(master_id);
CREATE INDEX ua_user_fk ON gc_user_access(user_id);
CREATE INDEX uaa_user_access_fk ON gc_user_access_active(user_access_id);
CREATE INDEX uaa_vid_fk ON gc_user_access_active(vid);
CREATE INDEX uae_user_access_fk ON gc_user_access_ext(user_access_id);
CREATE INDEX uae_user_access_managerid ON gc_user_access_ext(manager_id);
CREATE INDEX uai_t_user_access_fk ON gc_user_access_invite(target_access_id);
CREATE INDEX ual_user_access_fk ON gc_user_access_log(user_access_id);
CREATE INDEX uan_master_fk ON gc_user_answer(master_id);
CREATE INDEX uan_user_fk ON gc_user_answer(user_id);
CREATE INDEX uas_user_access_fk ON gc_user_access_share(user_access_id);
CREATE INDEX ue_event_id_FK ON gc_user_event(event_id);
CREATE INDEX ue_master_id ON gc_user_event(master_id);
CREATE INDEX ue_user_id_FK ON gc_user_event(user_id);
CREATE INDEX uer_event_fk ON gc_user_event_resource(event_id);
CREATE INDEX uer_user_fk ON gc_user_event_resource(user_id);
CREATE INDEX uf_event_id ON gc_user_fabulous(event_id);
CREATE INDEX uf_target_user_id ON gc_user_fabulous(target_user_id);
CREATE INDEX uf_user_id ON gc_user_fabulous(user_id);
CREATE INDEX uf_video_id ON gc_user_fabulous(video_id);
CREATE INDEX uid ON gc_user_stripe(user_id);
CREATE INDEX un_master_id ON gc_user_note(master_id);
CREATE INDEX un_user_fk ON gc_user_note(user_id);
CREATE INDEX un_video_fk ON gc_user_note(video_id);
CREATE INDEX unc_event_id ON gc_user_note_comment(event_id);
CREATE INDEX unc_file_id ON gc_user_note_comment(file_id);
CREATE INDEX unc_master_id ON gc_user_note_comment(master_id);
CREATE INDEX unc_user_fk ON gc_user_note_comment(user_id);
CREATE INDEX unique_context ON gc_master(context);
CREATE INDEX us_addby_user_id ON gc_user_schedule(addby_user_id);
CREATE INDEX us_sub_fk ON gc_user_schedule(sub_id);
CREATE INDEX us_video_id ON gc_user_schedule(video_id);
CREATE INDEX usc_folder_fk ON gc_user_save_content(folder_id);
CREATE INDEX usc_master_id ON gc_user_save_content(master_id);
CREATE INDEX usc_subject_fk ON gc_user_save_content(sub_id);
CREATE INDEX usc_user_fk ON gc_user_save_content(user_id);
CREATE INDEX usc_video_fk ON gc_user_save_content(video_id);
CREATE INDEX user_accrss_manager_FK ON gc_user_access(manager_id);
CREATE INDEX user_event_resource_file_id ON gc_user_event_resource(file_id);
CREATE INDEX user_event_resource_master_id ON gc_user_event_resource(master_id);
CREATE INDEX user_event_resource_target_id ON gc_user_event_resource(target_id);
CREATE INDEX user_event_resource_target_user_id ON gc_user_event_resource(target_user_id);
CREATE INDEX user_id_pid ON gc_user(pid);
CREATE INDEX user_node_comment_target_user_id ON gc_user_note_comment(target_user_id);
CREATE INDEX user_schedule_master_id ON gc_user_schedule(master_id);
CREATE INDEX user_ui_FK ON gc_user(info_id);
CREATE INDEX usf_file_id ON gc_user_save_folder(file_id);
CREATE INDEX usf_master_id ON gc_user_save_folder(master_id);
CREATE INDEX usf_user_fk ON gc_user_save_folder(user_id);
CREATE INDEX uum_master_fk ON gc_user_message(master_id);
CREATE INDEX uum_target_user ON gc_user_message(target_user_id);
CREATE INDEX uum_user_fk ON gc_user_message(user_id);
CREATE INDEX uva_file_id ON gc_user_video_action(file_id);
CREATE INDEX uva_sub_id ON gc_user_video_action(sub_id);
CREATE INDEX uva_user_fk ON gc_user_video_action(user_id);
CREATE INDEX uvp_master_fk ON gc_user_video_play(master_id);
CREATE INDEX uvp_user_fk ON gc_user_video_play(user_id);
CREATE INDEX uvp_video_fk ON gc_user_video_play(video_id);
CREATE INDEX vc_user_fk ON gc_video_comment(user_id);
CREATE INDEX vc_video_fk ON gc_video_comment(video_id);
CREATE INDEX video_comment_file_id ON gc_video_comment(file_id);
CREATE INDEX video_id ON sys_file_caption(video_id);
CREATE INDEX video_id_fk ON gc_event(video_id);
CREATE INDEX video_main_comment_id ON gc_video_comment(main_comment_id);
CREATE INDEX video_reply_comment_id ON gc_video_comment(reply_comment_id);
CREATE INDEX video_target_user_id ON gc_video_comment(target_user_id);
CREATE INDEX vpr_userVideoPlay_FK ON gc_user_video_plays_node(videoplay_id);
ALTER TABLE gc_access ADD CONSTRAINT access_admin_id FOREIGN KEY (admin_id) REFERENCES gc_access (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_access ADD CONSTRAINT access_package_img_id FOREIGN KEY (package_img_id) REFERENCES sys_file (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_access ADD CONSTRAINT access_package_video_file_id FOREIGN KEY (package_video_file_id) REFERENCES sys_file (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_master_active ADD CONSTRAINT active_video_id FOREIGN KEY (video_id) REFERENCES gc_video (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_file_caption ADD CONSTRAINT caption_file_id FOREIGN KEY (caption_file_id) REFERENCES sys_file (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE pt_tags ADD CONSTRAINT channel_file_tag_id FOREIGN KEY (file_id) REFERENCES sys_file (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE pt_channel_content ADD CONSTRAINT channel_fileid FOREIGN KEY (file_id) REFERENCES sys_file (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE pt_channel_subscribe ADD CONSTRAINT channel_subscribe FOREIGN KEY (channel_id) REFERENCES pt_channel (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE pt_channel_subscribe ADD CONSTRAINT channel_subscribe_user FOREIGN KEY (user_id) REFERENCES gc_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE pt_channel_content ADD CONSTRAINT channel_video_section FOREIGN KEY (section_id) REFERENCES pt_channel (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_chat_list ADD CONSTRAINT chat_master_id FOREIGN KEY (master_id) REFERENCES gc_master (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_chat_list ADD CONSTRAINT chat_user_id FOREIGN KEY (user_id) REFERENCES gc_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_chat_list ADD CONSTRAINT chat_video_id FOREIGN KEY (video_id) REFERENCES gc_video (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_video_comment ADD CONSTRAINT comment_master_id FOREIGN KEY (master_id) REFERENCES gc_master (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_feed_back ADD CONSTRAINT fb_user_fk FOREIGN KEY (user_id) REFERENCES gc_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_subject_tag_association ADD CONSTRAINT fk_association_master_id FOREIGN KEY (master_id) REFERENCES gc_master (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_subject_tag_association ADD CONSTRAINT fk_association_tag_id FOREIGN KEY (tag_id) REFERENCES gc_subject_tags (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE pt_tags ADD CONSTRAINT fk_channel_id FOREIGN KEY (channel_id) REFERENCES pt_channel (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE pt_view_subject ADD CONSTRAINT fk_master_id_pt FOREIGN KEY (master_id) REFERENCES gc_master (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE pt_tags ADD CONSTRAINT fk_resource_id FOREIGN KEY (resource_id) REFERENCES gc_resource (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE pt_tags ADD CONSTRAINT fk_subject_id FOREIGN KEY (subject_id) REFERENCES gc_subject (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE pt_view_subject ADD CONSTRAINT fk_subject_id_pt FOREIGN KEY (subject_id) REFERENCES gc_subject (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_file ADD CONSTRAINT fk_thumb_nail_id FOREIGN KEY (thumb_nail_id) REFERENCES sys_file (id) ON UPDATE SET NULL ON DELETE SET NULL;
ALTER TABLE gc_subject ADD CONSTRAINT fk_user_id FOREIGN KEY (create_user) REFERENCES gc_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE pt_view_subject ADD CONSTRAINT fk_user_id_pt FOREIGN KEY (user_id) REFERENCES gc_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE pt_tags ADD CONSTRAINT fk_video_id FOREIGN KEY (video_id) REFERENCES gc_video (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_group ADD CONSTRAINT g_master_id_FK FOREIGN KEY (master_id) REFERENCES gc_master (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_course_complete_read ADD CONSTRAINT gc_course_complete_read_subject_id FOREIGN KEY (subject_id) REFERENCES gc_subject (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_course_complete_read ADD CONSTRAINT gc_course_complete_read_user_id FOREIGN KEY (user_id) REFERENCES gc_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_event ADD CONSTRAINT gc_event_future_pre_event_id FOREIGN KEY (future_pre_event_id) REFERENCES gc_event (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_event ADD CONSTRAINT gc_event_link_file_id FOREIGN KEY (link_file_id) REFERENCES sys_file (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_event ADD CONSTRAINT gc_event_link_video_id FOREIGN KEY (link_video_id) REFERENCES gc_video (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_faq ADD CONSTRAINT gc_faq_id FOREIGN KEY (faq_id) REFERENCES gc_faq (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE pt_login_config ADD CONSTRAINT gc_master_id FOREIGN KEY (master_id) REFERENCES gc_master (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_master_sales_page ADD CONSTRAINT gc_master_sales_page_ibfk_2 FOREIGN KEY (subject_id) REFERENCES gc_subject (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_group_mentor ADD CONSTRAINT gc_mentor_group_id FOREIGN KEY (group_id) REFERENCES gc_group (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_group_mentor ADD CONSTRAINT gc_mentor_user_access_id FOREIGN KEY (user_access_id) REFERENCES gc_user_access (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_subject ADD CONSTRAINT gc_subject_alias_sub_id FOREIGN KEY (alias_sub_id) REFERENCES gc_subject (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_subject ADD CONSTRAINT gc_subject_fid FOREIGN KEY (fid) REFERENCES gc_subject (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_subject ADD CONSTRAINT gc_subject_sub_id FOREIGN KEY (sub_id) REFERENCES gc_subject (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_subject_tags ADD CONSTRAINT gc_tags_masterId FOREIGN KEY (master_id) REFERENCES gc_master (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_subject_tags ADD CONSTRAINT gc_tags_subId FOREIGN KEY (subject_id) REFERENCES gc_subject (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_video ADD CONSTRAINT gc_transcript_file_id FOREIGN KEY (transcript_file_id) REFERENCES sys_file (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_save_content_follow ADD CONSTRAINT gc_user_save_content_follow_folderid FOREIGN KEY (folder_id) REFERENCES gc_user_save_folder (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_save_content_follow ADD CONSTRAINT gc_user_save_content_follow_uid FOREIGN KEY (user_id) REFERENCES gc_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_video_play ADD CONSTRAINT gc_user_video_play_ibfk_1 FOREIGN KEY (file_id) REFERENCES sys_file (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_video_play ADD CONSTRAINT gc_user_video_play_ibfk_2 FOREIGN KEY (file_id) REFERENCES sys_file (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_video ADD CONSTRAINT gc_video_file_id FOREIGN KEY (file_id) REFERENCES sys_file (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_group ADD CONSTRAINT group_access_id FOREIGN KEY (access_id) REFERENCES gc_access (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_master_home_info ADD CONSTRAINT home_info_master_id FOREIGN KEY (master_id) REFERENCES gc_master (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_info ADD CONSTRAINT info_avatar_file_id FOREIGN KEY (avatar_file_id) REFERENCES sys_file (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_chat_history ADD CONSTRAINT list_chat_id FOREIGN KEY (list_chat_id) REFERENCES gc_chat_list (chat_id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_master_log ADD CONSTRAINT log_master_id_fk FOREIGN KEY (master_id) REFERENCES gc_master (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_manager ADD CONSTRAINT manager_master_FK FOREIGN KEY (master_id) REFERENCES gc_master (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_master_active ADD CONSTRAINT master_id FOREIGN KEY (master_id) REFERENCES gc_master (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_access ADD CONSTRAINT master_id_Fk FOREIGN KEY (master_id) REFERENCES gc_master (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_master_message ADD CONSTRAINT master_message_res_id FOREIGN KEY (res_id) REFERENCES gc_user_event_resource (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_master_message ADD CONSTRAINT master_message_target_user_id FOREIGN KEY (target_user_id) REFERENCES gc_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_master_message ADD CONSTRAINT master_message_user_answer_id_fk FOREIGN KEY (user_answer_id) REFERENCES gc_user_answer (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_master_message ADD CONSTRAINT master_message_user_id FOREIGN KEY (user_id) REFERENCES gc_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_master_message ADD CONSTRAINT master_message_user_schedule_id_fk FOREIGN KEY (user_schedule_id) REFERENCES gc_user_schedule (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_message ADD CONSTRAINT message_file_id FOREIGN KEY (file_id) REFERENCES sys_file (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_master_message ADD CONSTRAINT message_master_id_fk FOREIGN KEY (master_id) REFERENCES gc_master (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_note ADD CONSTRAINT note_file_id FOREIGN KEY (file_id) REFERENCES sys_file (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_paypal_info ADD CONSTRAINT paypal_master FOREIGN KEY (master_id) REFERENCES gc_master (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE pt_channel_content ADD CONSTRAINT pt_channel_content_ibfk_1 FOREIGN KEY (channel_id) REFERENCES pt_channel (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_master_pay_records ADD CONSTRAINT record_portal_id FOREIGN KEY (master_id) REFERENCES gc_master (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_master_pay_records ADD CONSTRAINT record_subject_id FOREIGN KEY (subject_id) REFERENCES gc_subject (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_master_pay_records ADD CONSTRAINT record_user_id FOREIGN KEY (user_id) REFERENCES gc_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_resource ADD CONSTRAINT res_video_id FOREIGN KEY (video_id) REFERENCES gc_video (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_master_sales_page ADD CONSTRAINT section_type_id FOREIGN KEY (section_type_id) REFERENCES gc_master_section_type (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_social_media ADD CONSTRAINT social_media_master_id FOREIGN KEY (master_id) REFERENCES gc_master (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_stripe_subscription ADD CONSTRAINT stripe_user_id FOREIGN KEY (user_stripe_id) REFERENCES gc_user_stripe (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_subject ADD CONSTRAINT sub_master_id FOREIGN KEY (master_id) REFERENCES gc_master (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_subject ADD CONSTRAINT subject_file_id FOREIGN KEY (sub_img_id) REFERENCES sys_file (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_subject_association ADD CONSTRAINT subject_import_master_id FOREIGN KEY (master_id) REFERENCES gc_master (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_subject_association ADD CONSTRAINT subject_import_subject_id FOREIGN KEY (subject_id) REFERENCES gc_subject (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_subject_intro_info ADD CONSTRAINT subject_intro_info_file_id FOREIGN KEY (file_id) REFERENCES sys_file (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_subject_intro_info ADD CONSTRAINT subject_intro_info_subject_id FOREIGN KEY (subject_id) REFERENCES gc_subject (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_stripe_subscription ADD CONSTRAINT subscription_master_id FOREIGN KEY (master_id) REFERENCES gc_master (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_file ADD CONSTRAINT sys_file_master_id FOREIGN KEY (master_id) REFERENCES gc_master (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_access ADD CONSTRAINT ua_access_fk FOREIGN KEY (access_id) REFERENCES gc_access (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_access ADD CONSTRAINT ua_master_id_fk FOREIGN KEY (master_id) REFERENCES gc_master (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_access ADD CONSTRAINT ua_user_fk FOREIGN KEY (user_id) REFERENCES gc_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_access_active ADD CONSTRAINT uaa_user_access_fk FOREIGN KEY (user_access_id) REFERENCES gc_user_access (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_access_active ADD CONSTRAINT uaa_vid_fk FOREIGN KEY (vid) REFERENCES gc_video (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_access_ext ADD CONSTRAINT uae_user_access_fk FOREIGN KEY (user_access_id) REFERENCES gc_user_access (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_access_ext ADD CONSTRAINT uae_user_access_managerid FOREIGN KEY (manager_id) REFERENCES gc_manager (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_access_invite ADD CONSTRAINT uai_t_user_access_fk FOREIGN KEY (target_access_id) REFERENCES gc_user_access (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_access_invite ADD CONSTRAINT uai_user_access_fk FOREIGN KEY (user_access_id) REFERENCES gc_user_access (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_access_log ADD CONSTRAINT ual_user_access_fk FOREIGN KEY (user_access_id) REFERENCES gc_user_access (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_answer ADD CONSTRAINT uan_event_fk FOREIGN KEY (event_id) REFERENCES gc_event (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_answer ADD CONSTRAINT uan_master_fk FOREIGN KEY (master_id) REFERENCES gc_master (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_answer ADD CONSTRAINT uan_user_fk FOREIGN KEY (user_id) REFERENCES gc_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_access_permission ADD CONSTRAINT uap_user_access_fk FOREIGN KEY (user_access_id) REFERENCES gc_user_access (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_access_share ADD CONSTRAINT uas_user_access_fk FOREIGN KEY (user_access_id) REFERENCES gc_user_access (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_event ADD CONSTRAINT ue_event_id_FK FOREIGN KEY (event_id) REFERENCES gc_event (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_event ADD CONSTRAINT ue_master_id FOREIGN KEY (master_id) REFERENCES gc_master (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_event ADD CONSTRAINT ue_user_id_FK FOREIGN KEY (user_id) REFERENCES gc_user (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE gc_user_event_resource ADD CONSTRAINT uer_event_fk FOREIGN KEY (event_id) REFERENCES gc_event (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_event_resource ADD CONSTRAINT uer_user_fk FOREIGN KEY (user_id) REFERENCES gc_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_fabulous ADD CONSTRAINT uf_event_id FOREIGN KEY (event_id) REFERENCES gc_event (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_fabulous ADD CONSTRAINT uf_target_user_id FOREIGN KEY (target_user_id) REFERENCES gc_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_fabulous ADD CONSTRAINT uf_user_id FOREIGN KEY (user_id) REFERENCES gc_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_fabulous ADD CONSTRAINT uf_video_id FOREIGN KEY (video_id) REFERENCES gc_video (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_stripe ADD CONSTRAINT uid FOREIGN KEY (user_id) REFERENCES gc_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_note ADD CONSTRAINT un_master_id FOREIGN KEY (master_id) REFERENCES gc_master (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_note ADD CONSTRAINT un_user_fk FOREIGN KEY (user_id) REFERENCES gc_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_note ADD CONSTRAINT un_video_fk FOREIGN KEY (video_id) REFERENCES gc_video (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_note_comment ADD CONSTRAINT unc_event_id FOREIGN KEY (event_id) REFERENCES gc_event (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_note_comment ADD CONSTRAINT unc_file_id FOREIGN KEY (file_id) REFERENCES sys_file (id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE gc_user_note_comment ADD CONSTRAINT unc_master_id FOREIGN KEY (master_id) REFERENCES gc_master (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_note_comment ADD CONSTRAINT unc_user_fk FOREIGN KEY (user_id) REFERENCES gc_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_schedule ADD CONSTRAINT us_addby_user_id FOREIGN KEY (addby_user_id) REFERENCES gc_user (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE gc_user_schedule ADD CONSTRAINT us_sub_fk FOREIGN KEY (sub_id) REFERENCES gc_subject (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_schedule ADD CONSTRAINT us_user_fk FOREIGN KEY (user_id) REFERENCES gc_user (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE gc_user_schedule ADD CONSTRAINT us_video_id FOREIGN KEY (video_id) REFERENCES gc_video (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_save_content ADD CONSTRAINT usc_folder_fk FOREIGN KEY (folder_id) REFERENCES gc_user_save_folder (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_save_content ADD CONSTRAINT usc_master_id FOREIGN KEY (master_id) REFERENCES gc_master (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_save_content ADD CONSTRAINT usc_subject_fk FOREIGN KEY (sub_id) REFERENCES gc_subject (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_save_content ADD CONSTRAINT usc_user_fk FOREIGN KEY (user_id) REFERENCES gc_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_save_content ADD CONSTRAINT usc_video_fk FOREIGN KEY (video_id) REFERENCES gc_video (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_group ADD CONSTRAINT user_access_id_fk FOREIGN KEY (user_access_id) REFERENCES gc_user_access (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_access ADD CONSTRAINT user_accrss_manager_FK FOREIGN KEY (manager_id) REFERENCES gc_manager (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_event_resource ADD CONSTRAINT user_event_resource_file_id FOREIGN KEY (file_id) REFERENCES sys_file (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_event_resource ADD CONSTRAINT user_event_resource_master_id FOREIGN KEY (master_id) REFERENCES gc_master (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_event_resource ADD CONSTRAINT user_event_resource_target_id FOREIGN KEY (target_id) REFERENCES gc_user_event_resource (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_event_resource ADD CONSTRAINT user_event_resource_target_user_id FOREIGN KEY (target_user_id) REFERENCES gc_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user ADD CONSTRAINT user_id_pid FOREIGN KEY (pid) REFERENCES gc_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_note_comment ADD CONSTRAINT user_node_comment_target_user_id FOREIGN KEY (target_user_id) REFERENCES gc_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_schedule ADD CONSTRAINT user_schedule_master_id FOREIGN KEY (master_id) REFERENCES gc_master (id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE gc_user ADD CONSTRAINT user_ui_FK FOREIGN KEY (info_id) REFERENCES gc_user_info (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_save_folder ADD CONSTRAINT usf_file_id FOREIGN KEY (file_id) REFERENCES sys_file (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_save_folder ADD CONSTRAINT usf_master_id FOREIGN KEY (master_id) REFERENCES gc_master (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_save_folder ADD CONSTRAINT usf_user_fk FOREIGN KEY (user_id) REFERENCES gc_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_message ADD CONSTRAINT uum_master_fk FOREIGN KEY (master_id) REFERENCES gc_master (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_message ADD CONSTRAINT uum_target_user FOREIGN KEY (target_user_id) REFERENCES gc_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_message ADD CONSTRAINT uum_user_fk FOREIGN KEY (user_id) REFERENCES gc_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_video_action ADD CONSTRAINT uva_file_id FOREIGN KEY (file_id) REFERENCES sys_file (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_video_action ADD CONSTRAINT uva_sub_id FOREIGN KEY (sub_id) REFERENCES gc_subject (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_video_action ADD CONSTRAINT uva_user_fk FOREIGN KEY (user_id) REFERENCES gc_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_video_action ADD CONSTRAINT uva_video_fk FOREIGN KEY (video_id) REFERENCES gc_video (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_video_play ADD CONSTRAINT uvp_master_fk FOREIGN KEY (master_id) REFERENCES gc_master (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_video_play ADD CONSTRAINT uvp_user_fk FOREIGN KEY (user_id) REFERENCES gc_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_video_play ADD CONSTRAINT uvp_video_fk FOREIGN KEY (video_id) REFERENCES gc_video (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_video_comment ADD CONSTRAINT vc_user_fk FOREIGN KEY (user_id) REFERENCES gc_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_video_comment ADD CONSTRAINT vc_video_fk FOREIGN KEY (video_id) REFERENCES gc_video (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_video_comment ADD CONSTRAINT video_comment_file_id FOREIGN KEY (file_id) REFERENCES sys_file (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE sys_file_caption ADD CONSTRAINT video_id FOREIGN KEY (video_id) REFERENCES gc_video (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_event ADD CONSTRAINT video_id_fk FOREIGN KEY (video_id) REFERENCES gc_video (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_video_comment ADD CONSTRAINT video_main_comment_id FOREIGN KEY (main_comment_id) REFERENCES gc_video_comment (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_video_comment ADD CONSTRAINT video_reply_comment_id FOREIGN KEY (reply_comment_id) REFERENCES gc_video_comment (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_video_comment ADD CONSTRAINT video_target_user_id FOREIGN KEY (target_user_id) REFERENCES gc_user (id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE gc_user_video_plays_node ADD CONSTRAINT vpr_userVideoPlay_FK FOREIGN KEY (videoplay_id) REFERENCES gc_user_video_play (id) ON UPDATE CASCADE ON DELETE CASCADE;
